config/routes.rb
Thejlb::Application.routes.draw do
  root "home#index"

  get "contact"           => "contact#index"
  get "about"             => "about#index"
  get "downloads"         => "downloads#index"
  get "metrix"            => "metrix#index"
  get "resume"            => "resume#index"
  get "blog"              => "blog#index"
  get "home"              => "home#index"

# Blog Routes
  get "blog/analysis_paralysis"
  get "blog/tealeaf_version_8_review"
  get "blog/why_you_should_keep_single_hit_sessions"
  get "blog/session_discard_events_for_bots"
  get "blog/how_to_use_tealeaf_to_analyze_bot_traffic"

  get "blog/tealeaf_sitecatalyst_integration"
  get "blog/what_are_you_doing_with_all_that_data"
  get "blog/how_to_capture_clicks_to_external_links"
  get "blog/datadrop_rules_for_bot_traffic"
  get "blog/monitoring_your_tealeaf_environment"

  get "blog/software_or_people_what_is_more_important"
  get "blog/why_integrate"
  get "blog/using_the_tealeaf_bot_dashboard_to_analyze_traffic"
  get "blog/drophit_rules_for_bot_traffic"
  get "blog/the_visitor_and_the_visit"
  
# Download Routes
  get "downloads/index"
  get "downloads/zipIconSet"
  get "downloads/zipFiddler2"
  get "downloads/pdf"
  get "downloads/doc"
  get "downloads/numeric_analytics"
  get "downloads/software"
  get "downloads/RTV8789"
  get "downloads/RTV8781"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
  end

  def zipIconSet
    send_file Rails.root.join('private', '48px_Icon_Set.zip'), :type=>"application/zip", :x_sendfile=>true
  end

  def zipFiddler2
    send_file Rails.root.join('private', 'Fiddler2Setup.zip'), :type=>"application/zip", :x_sendfile=>true
  end  

  def pdf
    send_file Rails.root.join('private', 'Rogelio Alvarado Vilchis.pdf'), :type=>"application/pdf", :x_sendfile=>true
  end

  def doc
    send_file Rails.root.join('private', 'Rogelio Alvarado Vilchis.docx'), :type=>"application/doc", :x_sendfile=>true
  end

  def RTV8789
    send_file Rails.root.join('private', 'RTV8789.zip'), :type=>"application/zip", :x_sendfile=>true
  end

  def RTV8781
    send_file Rails.root.join('private', 'RTV8789.zip'), :type=>"application/zip", :x_sendfile=>true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/metrix_controller.rb
class MetrixController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metrix_helper.rb
module MetrixHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/blog/analysis_paralysis.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Analysis Paralysis: <span class="badge">12-04-2012</span></h3>
		</div>
		<div class="panel-body">
			<h3>What is analysis paralysis?</h3>
			  <img src="/assets/Analysis-Paralysis.jpg" class="img-rounded", align="left"><p>This is the process of over-analyzing or over-thinking a situation to the point at which an action or decision is never taken.  Usually, any decision or action is treated as being over-complicated or there are too many options, so the choice is deferred, delayed, or never made.  Another way to look at analysis paralysis is that the person or organization is seeking the optimal or perfect solution, in fear of making a decision that may lead to an imperfect result.</p>

				<p>When it comes to analytics, analysis paralysis usually manifests itself through exceedingly long phases of planning, requirements gathering, design and modeling, with little or no extra value created by those steps. When these tasks extend over long periods of time, these processes emphasize the bureaucracies of the project or organization, while detracting from the project itself.</p>

				<p>This type of behavior is very similar to another paradox, the paradox of Buridan’s ass.  Buridan’s ass is a paradox in philosophy in the concept of free will, and refers to a hypothetical situation where an ass that is equally hungry and thirsty is placed precisely between a stack of hay and a pail of water. Since the paradox assumes the ass will always go to the item that is closer, it will die of both hunger and thirst since it cannot make a rational decision to choose either.</p>

				<img src="/assets/burdains_ass.jpg" class="img-rounded", align="right"><p>Analytics lends itself nicely to these two destructive ways of thinking (Analysis Paralysis & Buridan’s ass), because analytics is an imperfect science. Large bureaucracies and risk-adverse individuals tend to fall into the analysis paralysis trap, delaying a decision until all other options are gone. Because these types of organizations/people never want to make a less than perfect decision, they will analyze the issue until there is only one option left, effectively letting the analysis make the decision for you.</p>

				<p>While this approach may seem appealing to some, the last remaining option is rarely the best choice.  In extreme cases, the analysis paralysis approach can span months, or even years before a final decision is made.  Factor in the opportunity cost of delaying a decision, that could improve your conversion rate by as little as 1-2% for some large sites, and inaction may be a HUGE mistake!</p>

				<p>The imperfect science of analytics requires you to make decisions based on imperfect data.  Understanding and embracing this is going to keep you from falling into the analysis paralysis trap.  If you make decisions based on the data available, you can begin making gradual improvements to your website today.</p>

				<p>Remember, don’t get stuck in the paradox of Buridan’s ass when presented with multiple options.  You don’t always have to choose between option A or B, be creative and test both options!  Also, thinking in terms of opportunity cost will help get out of the analysis paralysis cycle, by attaching a cost to not making a decision.</p>

				<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/blog/datadrop_rules_for_bot_traffic.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">DataDrop rules for Bot Traffic <span class="badge">10-18-2011</span></h3>
		</div>
		<div class="panel-body">
		<h3>Processing/Canister Server - DataDrop Rules</h3>
		<p>The second option to drop Bot traffic is by utilizing the DataDrop pipeline agent on your Processing/Canister server.  DataDrop rules work in a very similar way as the DropHit rules above, with different formatting of the rules and the fact that these rules are set in the Transport Service Configuration , instead of in the Privacy Filter Configuration in TMS on your Processing/Canister server.  Within the Transport Service Configuration, the default configuration includes the DataDrop pipeline agent.  If you don't see the DataDrop pipeline agent included in your configuration, you will need to add it to be able to use this method of removing Bot traffic.</p>

		<p>In the following DataDrop rule, we are searching in the request buffer, specifically for the name HTTP_USER_AGENT containing Googlebot:</p>

		<ul><ul><ul>
		<li>Drop10=reqfield HTTP_USER_AGENT contains Googlebot</li>
		</ul></ul></ul>

		<p>The HTTP_USER_AGENT is a great way to identify Bot traffic, and thus, remove it from your Tealeaf pipeline.  While this is a great way to start tackling Bot traffic on your Tealeaf system, it is by no means the only way, and if you come up with a different name/value pair that works better for your environment and purposes, by all means, use it.  When creating your DataDrop rules, make them as broad/generic as possible to remove as much of the Bot traffic as possible without removing any wanted traffic.  This will take a little analysis on your part, but once you start looking at some of the Bot traffic on your system, you will quickly identify some common patterns that you can use to rid your system of Bot traffic.</p>

		<p>While it shouldn't be a problem, you can have a total of 100 DataDrop rules defined in your pipeline.  Remember, every additional rule you have means additional processing load on your server, so be aware of the impact of adding a bunch of rules in your pipeline.</p>

		<p>The DataDrop method of dropping Bot traffic is a good option if your PCA is heavily loaded and you want to distribute the processing of these rules to another server, or if you don't have access to the PCA servers for some reason.  Both of these methods are perfectly valid methods of getting rid of Bot traffic on your Tealeaf system.  The big difference between the first and second methods described are when you are dropping the traffic.  In the first method you are dropping the hits at the earliest point in the pipeline, while the second method you are dropping the hits after they have been forwarded from the capture server to the processing/canister server.</p>

		<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/blog/drophit_rules_for_bot_traffic.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">DropHit rules for Bot Traffic <span class="badge">10-18-2011</span></h3>
		</div>
		<div class="panel-body">
		<h3>Capture Server - DropHit rules for Bot Traffic</h3>
		<p>Method 1 utilizes DropHit rules in the privacy.cfg file on the Passive Capture Appliance (PCA). The important thing to note when using DropHit rules is that we are working with each individual hit as it comes into the system and evaluating each hit against the rules in our privacy.cfg file. Since these rules are on the PCA, the DropHit rules will eliminate the Bot hits at the earliest point in the Tealeaf pipeline, avoiding any additional processing that will occur as hits traverse the Tealeaf environment.  You can create these rules using the GUI interface on the PCA, or by editing the privacy.cfg file in its raw format.  I prefer to edit the raw file, but use what ever method you are most comfortable with.</p>

		<p>The following is an example DropHit rule as it would appear in the raw file:</p>

			<ul><ul><ul>
			<li>
				[Rule15]
				ReqField=HTTP_USER_AGENT
				ReqOp=CONTAINS
				ReqVal=Googlebot
				Enabled=True
				Actions=DropHit
				Description=Googlebot
			</li>
			</ul></ul></ul>

		<p>In this example, the rule is [Rule15].  For the privacy.cfg file, you can have up to 256 rules defined, and it is not recommended you use all 256.  Each new rule needs a unique number, and they do not need to be sequential, but it is nice to keep some sort of order when creating rules.  These rules are fairly low overhead for the system, because we are using a name/value pair found in the request to identify the Bot traffic.  The first field 'ReqField=' identifies the name/value pair we want to look at. The second field 'ReqOp=' indicates what we are matching in the ReqField, in this case we are looking for the ReqField to contain our value.  The third field 'ReqVal=' is the value we are looking for in the ReqField, and since the ReqOp is contains, it doesn't matter what other information may be in the ReqField value, as long as it contains our ReqVal.  The fourth field 'Enabled=' can be either True or False, and since we want this rule to drop the Googlebot hits, we set this to True.  The 'Actions=' directive can be any number of things, but for the purpose of this discussion, we want to use the built-in DropHit rule, which will drop the hit if this rule ([Rule15]) evaluates true, and the last item 'Description=' is optional, and allows you to provide additional information as to what this rule does.</p>

		<p>I like this method of getting rid of Bot traffic, because it eliminates the hits at the earliest point in the pipeline, but you need to be careful not to create too many rules that you overburden the PCA.  Remember, you have a maximum of 256 rules you can create, and it is not recommended you do this.  If your PCA is already experiencing high load, this may not be the best place to introduce more load by creating a bunch of DropHit rules.  The downside to this method is that once you drop these hits, they are gone forever, you cannot get them back and do any analytics on this data.</p>

		<p>This is my preferred method if you have additional processing power on your PCA, which is typically the case.  With a few carefully thought out DropHit rules, you can effectively eliminate the majority of your Bot traffic from ever getting into your Tealeaf system.</p>

		<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/blog/how_to_use_tealeaf_to_analyze_bot_traffic.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">How to use Tealeaf to Analyze your Bot/Crawler/Spider Traffic <span class="badge">10-17-2011</span></h3>
		</div>
		<div class="panel-body">
			<h3>Are they Useful?</h3>
			<p>The question you should be asking yourself with Bots/Crawlers/Spiders (Bots) is, what actionable insights are you driving by keeping these sessions in Tealeaf?  If you can't answer this question without giving it some thought, you probably don't need the hits/sessions cluttering up your Tealeaf system and using valuable disk space.  The reality is, you can gain some insights from this information like, who is indexing your site, and how well is our site being indexed, but this information is readily available from other, more reliable, sources.  For example, you can do a quick search on Google, using the site: command to see how well your site is being indexed.  Let's say, we want to find out how well www.buckknives.com  is indexed on Google.  To find out, you can open your browser to www.google.com, enter site:www.buckknives.com in the search field and hit enter.  By doing this, you discover Google found about 873 results (0.14 seconds).  If you know how many pages there are on your site, you can figure out pretty quickly how well your site is being indexed, and since we are talking about analytics here, you could calculate a quick ratio of how well your site is indexed as follows:</p>

			<ul><ul><ul><li>
			<p>Index Ratio = Pages Indexed / Total pages on your site </p>
			</li></ul></ul></ul>

			<p>Ideally, this ratio would be 1, and all the pages on your site would be indexed and searchable, but this is not usually the case.  Bots don't have the ability to crawl and index all the pages on every site, due to a number of limiting factors such as https, ajax, and flash to name a few.  In addition, you may have chosen to exclude certain pages from being indexed by using the robots.txt file.  In any case, you can figure out what our Index Ratio is fairly easily using the tools provided by the search engines crawling your site.</p>

			<p>If Tealeaf is your only analytics tool, which is pretty unlikely, you might want to store which Bots are crawling your site and what pages they are looking at, but I have yet to come up with a good reason to keep these sessions in your Long Term Canister (LTC) for replay.  Have you ever tried to replay a session generated by a Bot? If you have, you already know, most of these are single-hit sessions and those that aren't are about as exciting as watching paint dry.  For instance, you may want to know which Bots are crawling your site, and what pages are getting indexed, but I don't see much value in keeping these sessions around in the LTC for replay.  Aside from the overhead and additional disk space used by keeping these sessions around in your LTC, the existence of these sessions clouds your data.  Let's say, for simplicity sake, your site gets 100,000 sessions a day, and of these 10,000 are sessions created by Bots, or 10 percent of your sessions are not actual users of your site.  Combine this with all the other extraneous non-user traffic on your site and you can potentially be diluting your statistics pretty significantly.</p>

			<p>Since Bots are easy to identify, and don't provide a lot of actionable information you can't find from other sources, I prefer to drop these hits/sessions using one of the following methods:</p>

			<ul><ul><ul>
			<p><li><%= link_to "Capture Server - DropHit rules", "drophit_rules_for_bot_traffic#path" %></li>
			<li><%= link_to "Processing/Canister Server - DataDrop rules", "datadrop_rules_for_bot_traffic#path" %></li>
			<li><%= link_to "Event - Session Discard", "session_discard_events_for_bots#path" %></li></p>
			</ul></ul></ul>

			<p>Understanding each of these methods will help you determine which solution is the best option for your environment, based on your goals and objectives.</p>

				<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/blog/session_discard_events_for_bots.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Session Discard Events for Bots: <span class="badge">10-18-2011</span></h3>
		</div>
		<div class="panel-body">
			<h3>Tealeaf Event - Session Discard</h3>
			<p>In the final method, we use events to remove the Bot sessions from the processing/canister server before they are stored in the Long Term Canister (LTC).  To do this, we need to create the event(s) necessary to identify the Bot traffic, and we need a compound event that will drop the session once it is identified.  With this method, we can use the same field in the request HTTP_USER_AGENT to identify our Bots when creating events, or if you have installed the Traffic Analysis template from Tealeaf you can leverage the events.</p>

			<p>Once we have our events created to identify our Bot traffic, and we have validated they are working as expected, we can include these events in a Compound Session Discard Event.  The Compound Session Discard Event will remove the session if it matches any of the criteria events selected.  If you are already familiar with event creation, this should be a pretty simple operation for you, but there are some things you should be aware of before you chose this method to remove Bot traffic.</p>

			<p>When you use a Session Discard Event to keep traffic from getting to your LTC, these events are still counted as sessions in the Tealeaf system, as are any other events that have fired for that session.  In the interest of brevity, as if this blog isn't long enough already, I won't get into all the reasons why this is, just understand that this is one of the side-effects of using this method.  The discarded sessions will not be in your LTC, and you won't be able to replay these sessions, but all the event counts will be updated in the reporting database.</p>

			<p>If your primary goal is to save LTC disk space, this is an easy way to accomplish this task, as long as you don't mind the additional hits/sessions and event counts that will be stored in your reporting database.</p>

				<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/blog/using_the_tealeaf_bot_dashboard_to_analyze_traffic.html.erb
<div class="container"><br>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Using the Tealeaf Bot Dashboard to Analyze Traffic <span class="badge">10-21-2011</span></h3>
		</div>
		<div class="panel-body">
			<h3>Traffic Analysis - Bot Dashboard (Tealeaf v7.x)</h3>
			<p>Tealeaf has a number of templates available for version 7.x that can be imported into your environment.  These templates have not been updated for version 8.x as of this writing, but should be updated sometime in the near future.  The templates available for version 7 are:</p>

			<ol><ol><ol>
			<li>Business Analysis</li>
			<li>Traffic Analysis</li>
			<li>Usability Analysis</li>
			<li>Google Analytics</li>
			</ol></ol></ol>

			<p>Within these templates are a number of pre-built Scorecards, KPIs and Dashboards.  Some of these Scorecards, KPIs and Dashboards will require you to map or create events that align with the events in the report.  The two templates I use most frequently are the Traffic Analysis and Usability Analysis templates, which don't require you to map or create any events to get them up and running.</p>

			<p>The Traffic Analysis template provides three dashboards, Mobile Dashboard, Fixed Browser Dashboard, and Bot Dashboard.  These three dashboards segment the traffic on your system into Mobile Type, Browser Type or Bot type.</p>

			<p>In a previous article<b> Tealeaf and Bot/Crawler/Spider traffic:</b> I discuss the ways you can get rid of this traffic from reaching your Long Term Canister (LTC).  The Bot Dashboard is a great starting point to identify the Bots that are generating the largest amount of traffic on your site.  When using the Bot dashboard, I typically focus on the Bot Traffic pie chart.  When you drill-down into this chart from the dashboard, by default it will display the top 10 Bots with the most amount of visits to your site.  From the Event Chart view, you can drill-down to the session level to see the sessions generated by each Bot.  Viewing the session-level information is where you will find the information you need to create the rules necessary to remove Bot traffic from your system.</p>

			<p>If you are running a version 8.x Tealeaf system, and you can't wait for the template to come out, you will either have to search for specific Bots using the search feature, or you will have to create events that will identify Bots automatically.</p>

				<div class="center-x">
					<%= link_to blog_path, class: "btn btn-sm btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"> Back</span>
					<% end %>
				</div>

				<br>
		</div>
	</div>
</div>

<br><%= render 'layouts/navbar_blog' %>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/home/index.html.erb
<div class="page-header header-home">
	<div class="container">
		<div class="col-md-1"></div>
		<div class="col-md-10">
    <h2>Welcome</h2>
    <h4>to the new home of TheJLB.com! I have finally decided to consolidate
    everything under one common location, so please bare with me while I am getting
    everything in order. I will be adding new content and functionality over time,
    so please come back to checkout new features and functionality...</h4>
    </div>
	</div>
</div>

<div class='container'>
	<div class='col-md-4'>
		<div class='panel panel-default'>
			<div class='panel-body panel-home'>

				<h2>Resume</h2>
				<p>Revised and updated 8/14/2014 with links to view and download
				a copy from Google Docs and to my Linkedin profile. <b>Senoir/Management
				level analytics technologist.</b></p>

				<%= link_to resume_path, class: "btn btn-primary btn-sm pull-right" do %>
					View Resume &raquo;
				<% end %>

			</div>
		</div>
	</div>

	<div class='col-md-4'>
		<div class='panel panel-default'>
			<div class='panel-body panel-home'>

				<h2>Tealeaf Analytics Blog</h2>
				<p>Welcome to the new home of the Tealeaf Analytics Blog. The entries
				are identical to the blogspot Tealeaf-101, and is intended to be
				the new home of this blog going forward.</p>

				<%= link_to blog_path, class: "btn btn-primary btn-sm pull-right" do %>
					View Blog &raquo;
				<% end %>

			</div>	
		</div>
	</div>

	<div class='col-md-4'>
		<div class='panel panel-default'>
			<div class='panel-body panel-home'>

				<h2>Coming Soon!</h2>
				<p><b>Metrix:</b> Enterprise consulting services focused on 
				User/Customer Experience (CX/UX)</b></p>
				<p><b>MMA Metrix:</b> Predictive analytics for the sport of 
				Mixed Martial Arts(MMA).</p>

				<%= link_to metrix_path, class: "btn btn-primary btn-sm pull-right" do %>
					Learn more &raquo;
				<% end %>

			</div>	
		</div>
	</div>
</div>

<div class="container">
	<hr>
	<h3>Some more content...</h3>
	
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
  	<%= link_to "TheJLB", root_path, class: "navbar-brand" %>

  	  <ul class="nav navbar-nav">
        <li class="divider-vertical"></li>
        <li class="<%= 'active' if params[:controller] == 'home' %>"> <%= link_to "Home", root_path %></li>
        <li class="divider-vertical"></li>
        <li class="<%= 'active' if params[:controller] == 'blog' %>"> <%= link_to "Blog", blog_path %></li>
        <li class="divider-vertical"></li>
        <li class="<%= 'active' if params[:controller] == 'resume' %>"> <%= link_to "Resume", resume_path %></li>
        <li class="divider-vertical"></li>
        <li class="<%= 'active' if params[:controller] == 'metrix' %>"> <%= link_to "Metrix", metrix_path %></li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Downloads<b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to "Numeric Analytics", "/downloads/numeric_analytics" %></li>
	            <li><%= link_to "Software", "/downloads/software" %></li>
	            <li><%= link_to "Other Stuff", "#" %></li>
	            <li class="divider"></li>
	            <li><%= link_to "More Stuff", "#" %></li>
	            <li class="divider"></li>
	            <li><%= link_to "More Other Stuff", "#" %></li>
	          </ul>
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="divider-vertical"></li>
        <li class="<%= 'active' if params[:controller] == 'about' %>"> <%= link_to "About", about_path %></li>
        <li class="divider-vertical"></li>
      	<li class="<%= 'active' if params[:controller] == 'email' %>"> <%= link_to " ", '#', class: "glyphicon glyphicon-envelope" %></li>
        <li class="divider-vertical"></li>
      </ul>

  </div>
</nav>

app/views/layouts/_navbar_blog.html.erb

<div class='container'>
	<div class='col-md-3'></div>
	<div class='col-md-6' align='center'>
		<ol class="breadcrumb">
		  <li><%= link_to "Home", home_path %></li>
		  <li class="active">Blog</li>
		  <li><%= link_to "Resume", resume_path %></li>
		  <li><%= link_to "Metrix", metrix_path %></li>
		  <li><%= link_to "Downloads", downloads_path %></li>
		</ol>
	</div>
</div>

app/views/layouts/_navbar_downloads.html.erb

<div class='container'>
	<div class='col-md-3'></div>
	<div class='col-md-6' align='center'>
		<ol class="breadcrumb">
		  <li><%= link_to "Home", home_path %></li>
		  <li><%= link_to "Blog", blog_path %></li>
		  <li><%= link_to "Resume", resume_path %></li>
		  <li><%= link_to "Metrix", metrix_path %></li>
		  <li class="active">Downloads</li>
		</ol>
	</div>
</div>

app/views/layouts/_navbar_home.html.erb

<div class='container'>
	<div class='col-md-3'></div>
	<div class='col-md-6' align='center'>
		<ol class="breadcrumb">
		  <li class="active">Home</li>
		  <li><%= link_to "Blog", blog_path %></li>
		  <li><%= link_to "Resume", resume_path %></li>
		  <li><%= link_to "Metrix", metrix_path %></li>
		  <li><%= link_to "Downloads", downloads_path %></li>
		</ol>
	</div>
</div>

app/views/layouts/_navbar_metrix.html.erb
<div class='container'>
	<div class='col-md-3'></div>
	<div class='col-md-6' align='center'>
		<ol class="breadcrumb">
		  <li><%= link_to "Home", home_path %></li>
		  <li><%= link_to "Blog", blog_path %></li>
		  <li><%= link_to "Resume", resume_path %></li>
		  <li class="active">Metrix</li>
		  <li><%= link_to "Downloads", downloads_path %></li>
		</ol>
	</div>
</div>

app/views/layouts/_navbar_resume.html.erb
<div class='container'>
	<div class='col-md-3'></div>
	<div class='col-md-6' align='center'>
		<ol class="breadcrumb">
		  <li><%= link_to "Home", home_path %></li>
		  <li><%= link_to "Blog", blog_path %></li>
		  <li class="active">Resume</li>
		  <li><%= link_to "Metrix", metrix_path %></li>
		  <li><%= link_to "Downloads", downloads_path %></li>
		</ol>
	</div>
</div>